### ISSUE TITLE
Notice: Undefined variable: idtraining in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/output/renderable/training_management.php on line 73

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#1]
Après avoir essayé d'ajouter une première catégorie comme formation, au lieu de la page de confirmation j'obtiens :

> Notice: Undefined variable: idtraining in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/output/renderable/training_management.php on line 73

**Comment by mleconte** [comment]
Je vais définir cette variable avec une valeur défaut.

**Comment by mleconte** [comment]
Corrigé : définition de la variable avec une valeur par défaut dans training_management.php ligne 62
Commit 775a57df99115b44f466d4fb4905a231a4fbd77c
gestion de saut de page
