### ISSUE TITLE
Undefined property: stdClass::$typemod in .../training_milestones.php on line 128

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#10]
Après avoir joué avec le filtrage des types d'activités dans le formulaire de définition des jalons, j'ai obtenu le message d'erreur suivant : 

> Notice: Undefined property: stdClass::$typemod in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/output/renderable/training_milestones.php on line 128

Je crois que plus aucun item n'était sélectionné dans la liste déroulante au moment où j'ai cliqué sur [filtrer] pour rafraichir l'écran. Mais je n'en suis pas sur.

**Comment by dcadiou** [comment]
En complément, si on essait de re-sélectionner _Tous les types_ dans le champs _Type_, la sélection est prise en compte dans le sens où le bug n'apparaît plus. En revanche ce réglage est ignoré. Le formulaire continue donc de retourner une liste d'activités vides (mais avec les cours néanmoins). Le champs type lui se réaffiche comme si _Tous les types_ n'avait pas été sélectionné.

**Comment by dcadiou** [comment]
Autant pour moi, j'ai encore utilisé l'outil de travers !
En fait j'ai mal interprêté le champs _nom_ dans ce formulaire. J'y ai saisie le nom souhaité pour la formation, alors que ce n'est pas renseigné ici. Je viens de comprendre que le nom est le nom de l'activité sur lequel on veut filtrer.
Bref j'ai retiré le filtrage et je retrouve mes activités à renseigner. Donc plus de problème de ce coté.

En revanche, ce qui demeure est le fait qu'à l'ouverture ce formulaire ne filtre rien, mais ne sélectionne pas _Tous les types_ dans le champs _Type_. Si le bouton [Filtrer] est cliqué à ce moment-là, l'absence de type défini provoque le bug.

**Comment by dcadiou** [comment]
Dans un mail, Marc disait : 

> Je n'ai pas réussi à reproduire les issues #10 Undefined property: stdClass::$typemod in .../training_milestones.php on line 128

Effectivement, je viens d'installer Attestoodle sur notre plateforme de production et le bug ne se reproduit pas.

La principale différence entre nos 2 plateformes est le niveau de debug. Est-ce que ce bug n'apparait qu'au delà d'un certain niveau de debug ?

Au fait, j'ai oublié de préciser le commit concerné : 221919d

**Comment by cemu-guillaumegirard** [comment]
Ce genre de message est effectivement dépendant du niveau de debug configuré. 

Le message semble ne plus apparaître sur le commit a67def8. Je clos l'issue
