### ISSUE TITLE
Il manque des cours dans le formulaire de saisie des jalons

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#11]
En production, Attestoodle (commit 221919d) ne propose pas tous les cours dans le formulaire de saisie des jalons.
Il semble que l'exploration des sous-catégories de la formation ne fonctionne pas correctement.

**Comment by dcadiou** [comment]
La structure de la formation (1 niveau de sous-catégories, puis des cours) : 
![attestoodle-issue11-sc1](https://user-images.githubusercontent.com/25685520/47799777-3ce87680-dd2b-11e8-9437-5c2afe56af20.png)

Ce qui apparait dans le formulaire de saisie des jalons : 
![attestoodle-issue11-sc2](https://user-images.githubusercontent.com/25685520/47799923-8f299780-dd2b-11e8-8879-394ac95fc376.png)

J'ai essayé de cocher/décocher les 2 champs de filtrage _visible_ et _restriction_, mais ça ne corrige pas le problème.

Ce problème est vraiment bloquant pour notre mise en production, car tous les jalons de cette formation sont dans la sous-catégorie _Votre espace d'accueil et d'accompagnement_, plus précisément dans le cours _FOAD - (WEBCGE) Votre espace d'accueil et d'accompagnement_, qu'on ne peut pas gérer.

**Comment by mleconte** [comment]
Seul les cours avec suivis d'achèvement sont présentés. Est-ce que les autres cours possèdent le suivi d'achèvement ?

**Comment by dcadiou** [comment]
Salut Marc.
Quand tu parles d'"_achèvement_", parles-tu : 
- d'_achèvement de cours_
ou
- d'_achèvement d'activités_ ?

Quoi qu'il en soit, pour les cours que j'ai regardé dans la formation, ceux qui sont présentés dans la gestion des jalons ou ceux qui en sont absents : 
- aucun n'a d'achèvement de cours
- tous ont de l'achèvement d'activités, avec plus de critères pour ceux qui sont ignorés par la gestion des jalons.

Bref ça ne me parait pas être une bonne piste.

**Comment by mleconte** [comment]
Le bug est corrigé par le commit 5f41a04, apparemment le code récursif était en cause, sans test unitaire il est difficile de le débugguer, aussi je l'ai remplacé par la requête SQL que j'avais soumis à Guillaume.
