### ISSUE TITLE
Rendre les activités cliquables dans le fomulaire de gestion des jalons

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#12]
Il serait très pratique de pouvoir cliquer sur une activité dans le formulaire de gestion des jalons et que la fenêtre d'édition de ses paramètres s'ouvre (dans un nouvel onglet par exemple).

Quand on gère les jalons on peut avoir besoin d'en savoir plus sur l'activité candidate.

**Comment by cemu-guillaumegirard** [comment]
Added <a> link in activities list 

(commit 837cb7b)
