### ISSUE TITLE
Améliorer l'ergonomie du filtre d'activité de la gestion des jalons

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#13]
Plusieurs points rendent l'usage du filtre d'activités un peu difficile à appréhender spontanément : 

- Tel qu'expliqué dans la [doc technique](https://sourcesup.renater.fr/wiki/attestoodle/_media/doc:dossier_technique.pdf), certains filtres sont prioritaires sur d'autres. Il serait plus simple que ce soit un simple ET
- Il faudrait pouvoir choisir '_tous_' pour le filtre sur la visibilité 
- idem pour le filtre sur les activités avec restrictions d'accès ou non
- quand '_tous les types_' est actif, l'item n'est pas sélectionné, donc on ne le sait pas de prime abord
- le terme 'restriction' est un peu trop succint, pourquoi ne pas mettre 'avec restriction'
- pour bien montrer que le filtrage s'applique aux activités et non aux cours, je propose de renommer le bouton 'Filtrer' en 'Filtrer les activités'

**Comment by dcadiou** [comment]
Marc vient de me répondre par mail : 

> Bonjour
> Je viens de comprendre pourquoi tu ne vois pas ce qui est sélectionné dans le filtrage des jalons quand 'Tous les types' est sélectionné
> en fait il s'agit de votre thème qui pose problème sur les listes à sélections.
> Si tu consulte la capture d'écran que j'ai réalisé (cf pièce jointe) on à un affichage plus lisible, je vais demain au Mans j'en parlerai à Jonathan.
> Peux-tu me rappeler le thème que vous utilisez ?
> Et est-ce que les autres listes, de votre instance de Moodle, par exemple "choisir un pays" lors de la création/modification d'un utilisateur, sont présentées entièrement ouvertes ou sont-elles imitées à une seule ligne ?
> Cordialement

![image](https://user-images.githubusercontent.com/25685520/48134754-37df7600-e29b-11e8-87dc-4326c4c4bed7.png)

**Comment by jonathanjoegit** [comment]
Salut !

On utilise boost. Tu viens demain ? Je ne serai pas là l’après midi par contre...
Bonne journée

Jonathan Jupin
Développements informatiques
Pôle Ressources Numériques
Tél. +33 (0)2 43 83 30 31
Avenue Olivier Messiaen, 72085 - LE MANS Cedex 09
univ-lemans.fr <http://univ-lemans.fr/> <https://www.facebook.com/LeMansUniversite>  <https://twitter.com/LeMansUniv>

**Comment by dcadiou** [comment]
Nous utilisons le thème '_essential_'.
Je n'ai pas remarqué que nous ayons ce problème sur d'autres réglages de la plateforme.
Par exemple, le choix du pays dans mon profil apparait comme ça : 
![image](https://user-images.githubusercontent.com/25685520/48134916-b5a38180-e29b-11e8-8066-05a07a1dd719.png)

En revanche, il est vrai que je crois que nous avons avons ce problème avec toutes les autres listes déroulantes du plugin Attestoodle. Est-ce qu'Attestoodle utilise des types de listes particulières qui ne seraient pas compatibles avec notre thème ?

**Comment by cemu-guillaumegirard** [comment]
Formulaire de filtre amélioré.
(commit 1e1f3ad)
