### ISSUE TITLE
Un paramètre requis (categoryid) est manquant

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#16]
Quand on est dans le rapport global et qu'on essait de modifier le filtrage des dates, au moment de la validation, une erreur apparait (voir ci-après). 
La modification des dates n'a alors pas lieu.

![image](https://user-images.githubusercontent.com/25685520/48268579-a48e7800-e435-11e8-91d8-6117f1442edd.png)

Même avec les droits administrateur, ce problème existe. Il ne s'agit donc très probablement pas d'une problématique de droits.

Ce bug n'est pas bloquant, car Il existe la solution de contournement suivante : 

1. Aller dans le détail d'un étudiant
2. Y-modifier le filtrage par date
3. Générer son attestation
4. Retourner dans le rapport global, les dates doivent alors avoir été changées avec succès.

Version utilisée : 7dc6853.

**Comment by mleconte** [comment]
Je prend en compte et je vais le corriger début semaine prochaine, ce paramètre est nécessaire au fil d’Ariane, en changeant les dates on rappel la page et j'ai omis ce paramètre.

**Comment by mleconte** [comment]
Corrigé par le commit  352cc5e
