### ISSUE TITLE
Did you remember to make the first column something unique in your call to get_records? Duplicate value '84424' found in column 'id'.

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#17]
Sur mon Moodle dockerisé, j'ai un message d'erreur qui se répète de très nombreuses fois dans la page : 

> Did you remember to make the first column something unique in your call to get_records? Duplicate value '...' found in column 'id'.

Par exemple : 

![image](https://user-images.githubusercontent.com/25685520/48275874-e673ea00-e446-11e8-8a30-470c7d5adf46.png)

Cela se produit, entre autres, quand je clique sur générer les attestations, mais pas uniquement.

Je suis sur la version f7750cd.

**Comment by mleconte** [comment]
Devrait être corrigé par le commit 8e613c0
Il s'agit d'une ancienne requête qui ne prend pas en compte les doublons issue d'une double inscription a un cours.

**Comment by cemu-guillaumegirard** [comment]
Corrigé.
(commit 8e613c0)
