### ISSUE TITLE
Messages d'erreur en arrivant sur la page admin/tool/capability/index.php

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#2]
Quand j'essaie de consulter le rapport de capacité, j'obtiens les messages d'erreurs suivant. Pourtant mon utilisateur a le rôle admin sur le système.

> Invalid get_string() identifier: 'attestoodle:deletetemplate' or component 'tool_attestoodle'. Perhaps you are missing $string['attestoodle:deletetemplate'] = ''; in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/lang/en/tool_attestoodle.php?
> 
>     line 349 of /lib/classes/string_manager_standard.php: call to debugging()
>     line 7089 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
>     line 2452 of /lib/accesslib.php: call to get_string()
>     line 44 of /admin/tool/capability/index.php: call to get_capability_string()
> 
> Invalid get_string() identifier: 'attestoodle:managetemplate' or component 'tool_attestoodle'. Perhaps you are missing $string['attestoodle:managetemplate'] = ''; in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/lang/en/tool_attestoodle.php?
> 
>     line 349 of /lib/classes/string_manager_standard.php: call to debugging()
>     line 7089 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
>     line 2452 of /lib/accesslib.php: call to get_string()
>     line 44 of /admin/tool/capability/index.php: call to get_capability_string()
> 
> Invalid get_string() identifier: 'attestoodle:viewtemplate' or component 'tool_attestoodle'. Perhaps you are missing $string['attestoodle:viewtemplate'] = ''; in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/lang/en/tool_attestoodle.php?
> 
>     line 349 of /lib/classes/string_manager_standard.php: call to debugging()
>     line 7089 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
>     line 2452 of /lib/accesslib.php: call to get_string()
>     line 44 of /admin/tool/capability/index.php: call to get_capability_string()

**Comment by dcadiou** [comment]
Par ailleurs, une fois le rapport de capacité affiché, les 3 permissions citées dans les messages d'erreur n'aparraissent pas pareil dans le tableau du rapport. Ils sont libellés avec entre double crochets. Par exemple :

> [[attestoodle:deletetemplate]]tool/attestoodle:deletetemplate

Il manque peut être des traductions dans les fichiers lang.

**Comment by mleconte** [comment]
Corrigé dans le commit 775a57df99115b44f466d4fb4905a231a4fbd77c
gestion saut de page
