### ISSUE TITLE
Listes déroulantes continuellement développées sur une grande hauteur

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#20]
Avec notre thème (Essential), les listes déroulantes sont présentées développées. Cela massacre l'ergonomie.

Même avec la version f7750cd, c'est encore le cas.

![image](https://user-images.githubusercontent.com/25685520/48277477-17561e00-e44b-11e8-9309-7f09d14d87a4.png)

**Comment by mleconte** [comment]
la seule liste éventuellement corrigée, est celle du filtre des activités jalons, sur les types à prendre en compte. Merci de tester **cette** liste, je ne vais pas corrigé l'ensemble des listes si la solution n'est pas efficace.

**Comment by mleconte** [comment]
Le commit 2dafbb6 devrait corriger les liste déroulantes affichées ci-dessus.

**Comment by dcadiou** [comment]
OK.

Du coup j'ai vérifié là où tu as dit : 
![image](https://user-images.githubusercontent.com/25685520/48343296-4d291b80-e672-11e8-82e9-3f433f048f69.png)

La correction semble efficace (en version 7b68edf).

Du coup, je pense que tu peux l'étendre.

**Comment by mleconte** [comment]
Correction étendu au reste du code commit 853a020
