### ISSUE TITLE
Ambiguité du filtrage de da

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#21]

**Comment by dcadiou** [comment]
Dans le formulaire de filtrage des dates, dans le rapport global ou dans le rapport détaillé, l'utilisateur peut légitimement se demander si la permière date démarre à 0h ou à 24h (donc inclus ou exclus). Idem pour la deuxième date.

Il faudrait, je pense, éviter que les gens aient à aller voir dans la doc pour le savoir.

Ne pourrais-t-on pas ajouter après '_Du (la date)..._' : "**_(inclut)_**" 
et après '_au (la date...)_' : "**_(inclut)_**"
Et éventuellement un texte explicatif qui s'afficherait sous forme d'info bulle, quand on passe la souris sur une icone point d'interrogation. Le même type d'info bulle d'aide qu'on trouve dans les paramétrages ordinaires de Moodle.

![image](https://user-images.githubusercontent.com/25685520/48354392-e582c880-e691-11e8-967a-475d5b8f4b89.png)

Ce texte pourrait par exemple préciser "**_Les dates indiquées précisent la période d'analyse en commençant par le premier jour dès la première heure (0h00), jusqu'au dernier jour à la dernière heure (24h00)_**"

**Comment by mleconte** [comment]
Mise en place avec le commit b73f48a
