### ISSUE TITLE
Listage des formations trop lent sur des grosses plateforme

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/attestoodle#24]
### [Copied from initial repository]

**dcadiou commented on 26 Apr:** 

> Quand on clic sur [gestion de formations], Attestoodle présente la liste des catégories qui pourraient être déclarées 'formation' au sens Attestoodle.
> 
> Sur un gros site comme lecampus-pp de l'université de Caen, cela occupe le processeur du serveur à 100% pendant 1 min 15. L'utilisateur est donc obligé d'attendre tout ce temps avant de pouvoir déclarer une formation. Plus grave, avec un CPU à 100%, les autres utilisateurs doivent aussi être bloqués !
>
>(voir tache redmine https://redmine.unicaen.fr/Etablissement/issues/13387)

**cemu-guillaumegirard commented on 27 Apr:** 

> Le problème est même présent sur toutes les pages.
> 
> Plusieurs pistes d'améliorations :
> - Remplacer la création de la listes des catégories dans index.php par la création uniquement des formations (trainings)
> - Remplacer la récursivité pour la création de l'arborescence des catégories par une requête en BDD en se basant sur le champ "path"
> - Utiliser le cache pour stocker les objets PHP afin d'éviter de reconstruire l'arbre à chaque page

 **cemu-guillaumegirard commented on 5 Jun:**

> Problème reproduit sur plateforme de test en ajoutant 10000 catégories.
> J'ai remplacé la création de la liste des catégories par uniquement la liste des formations, ce qui évite aux pages autre que "trainings management" de planter.
> 
> Améliorations possibles :
> - Paginer la page trainings management
> - Ne laisser qu'un champ de recherche sur cette page
> - Pouvoir déclarer une formation depuis la page d'une catégorie plutôt que sur une page unique (déclaration une à une)

**Comment by mleconte** [comment]
Le chargement des catégories est supprimé, reste des le chargement de l'ensemble des formations (lors de la gestion des formations) qui faudra paginer. Pour clore ce point il faut déterminer si on créer un nouveau role pour la gestion des formations, ou si on n'affiche que les formations en fonction des droits par catégories accordé aux utilisateurs (gestionnaire de catégorie)

**Comment by cemu-guillaumegirard** [comment]
Le problème semble corrigé
(commit f215edf)
