### ISSUE TITLE
Difficultés d'accès au plugin pour les non admins

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#3]
Sur notre plateforme de préprod, quand une personne, qui n'est pas admin essaie d'administrer une formation attestoodle (par exemple ses jalons), elle obtiens le message :

> Désolé, vous n'avez actuellement pas les droits d'accès requis pour effectuer ceci (Ajouter/Supprimer une formation)
> 
> Plus d'informations sur cette erreur
> Debug info:
> Error code: nopermissions
> Stack trace:
> 
>     line 825 of /lib/accesslib.php: required_capability_exception thrown
>     line 73 of /admin/tool/attestoodle/index.php: call to require_capability()
> 
> 

Je précise son rôle est gestionnaire, mais pas au niveau système, au niveau d'une catégorie parente de celle qui contient la catégorie, déclarée comme formation, et à administrer.

**Comment by jonathanjoegit** [comment]
J'ai vu ça aussi. Obligé de mettre Nathalie Barrault "administrateur de la plateforme" pour l'accès à Attestoodle dans la panneau admin.

**Comment by dcadiou** [comment]
Je pense que c'est maintenant corrigé, au moins en partie.
Je laisse Marc préciser les n° de commit des corrections.

**Comment by mleconte** [comment]
corrigé partiellement avec le commit 2fb6af8 "droits des gestionnaires de catégorie"

**Comment by dcadiou** [comment]
Je viens d'essayer le plugin (commit 221919d) avec Muriel Paris, l'ingénieur pédagogique qui sera la première à Caen à utiliser "pour de vrai" Attestoodle sur un parcours en poduction.

Bien qu'étant gestionnaire, elle n'a pas pu déclarer sa formation à Attestoodle.

Elle avait bien accès au formulaire avec la case à cocher pour déclarer la formation, mais quand elle cliquait sur [enregistrer], le même formulaire se réaffichait sans plus de champs qu'avant et avec la case à cocher toujours décochée. Bref son action n'avait aucun effet.
En conséquence elle ne pouvait pas accéder à tous les autres réglages, notamment à ce qu'elle voulait faire, saisir les jalons.
Je me suis connecté en mon nom, donc en tant qu'admin, j'ai coché la case pour déclarer la formation. Le comportement n'a pas été le même. Cette fois quand le formulaire s'est réaffiché, la case était cochée et surtout tous les nouveaux champs devenaient disponibles.
Je me suis déconnecté. Muriel s'est reconnecté. Cette fois, elle a accès à tous les réglages et en particulier la gestion des jalons.

Aurait-elle le droit de modifier une formation, mais pas de la déclarer ?

Quelques précisions : 
* La catégorie que nous avons déclaré comme "formation" est une sous-sous-catégorie : 
  _IAE Caen_ (niveau 1)
    _DU_ (niveau 2)
       _(CGEUCA801) DU Capacité de Gestion des Entreprises_ (niveau 3)

* Muriel a un rôle gestionnaire dans la catégorie de premier niveau _IAE Caen_, et indirectement dans toutes les sous-catégories. Elle n'a pas de rôle gestionnaire explicitement déclaré dans la catégorie  _(CGEUCA801) DU Capacité de Gestion des Entreprises_.

En conclusion, ce bug n'est pas bloquant tant qu'un administrateur est disponible pour déclarer la formation la première fois. Je pense néanmoins, qu'il serait mieux que les gestionnaires puissent être 100% autonomes là-dessus.

**Comment by mleconte** [comment]
corrigé par le commit 18adbf4
