### ISSUE TITLE
ZIP incomplet lorsqu'une formation comprend des étudiant en N et N-1

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/attestoodle#30]
Problème relevé sur la plateforme du Mans.
**Contexte :**
La formation testée comprend des inscrits sur l'année N et des inscrits sur l'année N-1. Il s'agit de la même formation (même catégorie de cours Moodle) avec donc les inscrits de l'année précédente et ceux de l'année en cours. Le rapport global de la formation montre ~140 inscrits au total contre un total d'environ 40 inscrits pour l'année courante.

**Fonctionnalités utilisées :**
Génération d'attestation en lot + téléchargement de toutes les attestations existantes (ZIP)

**Comportement attendu :**
Le fichier ZIP contient l'intégralité des attestations (inscrit en N et en N-1)

**Comportement observé :**
Il semblerait que le fichier ne comporte que les attestations des inscrits en N-1. 
En revanche il semble que toutes les attestations (N et N-1) soient bien générées : lors de la consultation du détail d'un inscrit en année N, le plug-in propose le lien "Télécharger l'attestation".

**Comment by mleconte** [comment]
Après visualisation de l'erreur, il s'agit d'un problème de performance, le délai de 30 seconde est dépassé !!
Certes la plateforme de test n'est pas optimisée, mais elle n'est pas dégradée volontairement, il faut donc corriger le problème de perf avant la publication !!

**Comment by cemu-guillaumegirard** [comment]
Corrigé sur master.
(commit 5356a8d)
