### ISSUE TITLE
bug sur l'aperçu d'un modèle

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#31]
Sur notre préprod, dans une page de configuration d'une formation (admin/tool/attestoodle/index.php?page=trainingmanagement&categoryid=15592&call=categ), quand on clique sur le bouton [aperçu] pour prévisualiser le modèle associé à la formation (modèle spécifique IAE), le message d'erreur ci-dessous s'affiche.

> Exception : TCPDF ERROR: Some data has already been output, can't send PDF file

![image](https://user-images.githubusercontent.com/25685520/50162865-9575d200-02df-11e9-8d39-0d09784fd1d2.png)

Bug constaté sur le commit a67def8.

**Comment by cemu-guillaumegirard** [comment]
Bug également reproduit au clic sur **Aperçu** dans la page de création d'un nouveau modèle

**Comment by cemu-guillaumegirard** [comment]
Corrigé sur develop en même temps que #33 
(commit 586196b)
