### ISSUE TITLE
Undefined index: visibmod in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/forms/training_milestones_update_form.php

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#32]
Après avoir saisie des jalons, une fois le bouton d'enregistrement cliqué : 
J'ai une avalanche de messages (297 en tout) : 

> Notice: Undefined index: visibmod in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/forms/training_milestones_update_form.php on line ...
ou 
> Notice: Undefined index: restrictmod in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/forms/training_milestones_update_form.php on line ...

**Comment by dcadiou** [comment]
Le détail des "erreurs" affichées : 
[attestoodle_issue32.txt](https://github.com/grp-attestoodle/attestoodle/files/2691200/attestoodle_issue32.txt)

Il y a 197 `notices` relatives à `visibmod` et 99 relatives à `restrictmod`.

Plus une autre : 
> Undefined property: stdClass::$filter in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/output/renderable/training_milestones.php on line 133

**Comment by dcadiou** [comment]
Commit courant : a67def8

**Comment by cemu-guillaumegirard** [comment]
Corrigé sur develop
(commit dd64211)
