### ISSUE TITLE
Notice: Undefined variable: minwidth in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/simul_pdf.php on line 90

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#33]
Après avoir généré une attestation dans la page de détail d'un étudiant (https://lecampus-pp.unicaen.fr/admin/tool/attestoodle/index.php?page=learnerdetails&action=generatecertificate&categoryid=15592&learner=85273&categorylnk=15592&begindate=2018-01-01&enddate=2018-12-31), ce message est apparu une fois : 

> Notice: Undefined variable: minwidth in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/simul_pdf.php on line 90

Commit courant : a67def8

**Comment by dcadiou** [comment]
Le warning se produit une fois par attestation générées. Si génération en lot, la page est remplie de warnings.

**Comment by mleconte** [comment]
Attention vous répétez les mêmes erreurs (variable minwidth undefined) que l'issue #31

**Comment by cemu-guillaumegirard** [comment]
Corrigé sur develop
(commit 586196b)
