### ISSUE TITLE
undefined index: input_name_prefix ...

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#34]
Ce message apparait furtivement lors du changement de page du bilan global des apprenants (https://lecampus-pp.unicaen.fr/admin/tool/attestoodle/index.php?page=learners&categoryid=15592&begindate=2018-01-01&enddate=2018-12-31&categorylnk=15592) vers une page de détail (https://lecampus-pp.unicaen.fr/admin/tool/attestoodle/index.php?page=learnerdetails&learner=87482&begindate=2018-01-01&enddate=2018-12-31&categorylnk=15592) et vice versa.

![image](https://user-images.githubusercontent.com/25685520/50166280-040a5e00-02e7-11e9-9d9e-aaf0e25f68d8.png)

**Comment by cemu-guillaumegirard** [comment]
Corrigé sur develop en même temps que #36
(commit 10a5028)
