### ISSUE TITLE
Invalid get_string() identifier

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/attestoodle#35]
Ce message d'erreur apparait en essayant d'utiliser le filtre d'activité sur la page de gestion des jalons (activités "Devoir" sélectionnée puis clique sur "Filtrer")
```
Invalid get_string() identifier: 'modulename' or component 'questionnaire'. Perhaps you are missing $string['modulename'] = ''; in mod/questionnaire/lang/en/questionnaire.php?

    line 349 of /lib/classes/string_manager_standard.php: call to debugging()
    line 7128 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
    line 250 of /admin/tool/attestoodle/classes/forms/training_milestones_update_form.php: call to get_string()
    line 46 of /admin/tool/attestoodle/classes/forms/training_milestones_update_form.php: call to tool_attestoodle\forms\training_milestones_update_form->get_elements()
    line 204 of /lib/formslib.php: call to tool_attestoodle\forms\training_milestones_update_form->definition()
    line 75 of /admin/tool/attestoodle/classes/output/renderable/training_milestones.php: call to moodleform->__construct()
    line 98 of /admin/tool/attestoodle/index.php: call to tool_attestoodle\output\renderable\training_milestones->__construct()
```

J'ai en réalité 26 fois l'erreur d'affichée avec une info différente au niveau de **or component 'questionnaire'** où "questionnaire" varie. Le reste est identique à l'erreur ci-dessus.

La page me dit **Erreur de sortie. La redirection automatique a été désactivée.** et me propose de cliquer sur "Continuer". En cliquant je me retrouve sur la page de gestion des jalons avec les mêmes 26 erreurs. 

Il semble cependant que le filtre soit tout de même appliqué corectement : la liste me propose, en l'occurence, uniquement les activités de type Devoir.

**Comment by mleconte** [comment]
L'erreur précise bien que c'est votre plugin questionnaire qui n'est pas correct !
Les plugins sont tenu d'avoir leur nom dans leur fichier de langue !!
Après vérification le plugin "questionnaire" du dépôt Moodle contient bien ce code 
$string['modulename'] = 'Questionnaire';
Donc vérifier votre installation et la santé de vos disques !

**Comment by cemu-guillaumegirard** [comment]
Invalide.
