### ISSUE TITLE
Au changement de dates : Invalid array parameter detected in required_param()

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#38]
Après avoir modifié les dates de début et de fin du filtre pour générer les attestations sur une autre période, j'obtiens les messages d'erreur quand la page s'actualise : 

> Invalid array parameter detected in required_param(): input_begin_date
> 
>     line 662 of /lib/moodlelib.php: call to debugging()
>     line 109 of /admin/tool/attestoodle/index.php: call to optional_param()
> 
> Invalid array parameter detected in required_param(): input_end_date
> 
>     line 662 of /lib/moodlelib.php: call to debugging()
>     line 110 of /admin/tool/attestoodle/index.php: call to optional_param()

Commit courant : a67def8

**Comment by cemu-guillaumegirard** [comment]
Corrigé sur develop
(commit baec9b2)
