### ISSUE TITLE
Erreur à la génération d'attestations

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#39]
Quand j'essaie de générer les attestations dans une formation de mon Moodle dockerisé, j'obtiens le message d'erreur suivant pour chaque attestation : 

> Notice: Trying to get property of non-object in /var/www/html/moodle/admin/tool/attestoodle/classes/gabarit/attestation_pdf.php on line 97

Puis une notification indiquant : 

> An error occured while attempting to generate certificates, try again later
> All 37 files in error 

Remarque : dans ce parcours, lors de mes essais, tous les étudiants avaient un temps à 0 (parce que la copie des données de prod a été faite avant ou au démarrage du parcours, les étudiants n'ont donc pas eu le temps d'achever des activités). J'imagine que ce n'est pas sans lien.

Commit de cette version sous docker : df7a5b5

**Comment by dcadiou** [comment]
Je suis maintenant sur le commit a67def8 et le problème est toujours là.

**Comment by dcadiou** [comment]
J'ai l'impression que cela vient de l'absence de modèle. Quand j'essaie d'avoir un aperçu du modèle, j'obtiens : 

> Error

 reading from database
Plus précisément : 

> Debug info: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
> select type,data from mdl_tool_attestoodle_tpl_detail where templateid =
> [array (
> )]

> Stack trace:
> 
>     line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
>     line 1184 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
>     line 137 of /admin/tool/attestoodle/classes/gabarit/attestation_pdf.php: call to mysqli_native_moodle_database->get_recordset_sql()
>     line 97 of /admin/tool/attestoodle/classes/gabarit/attestation_pdf.php: call to tool_attestoodle\gabarit\attestation_pdf->set_idtemplate()
>     line 73 of /admin/tool/attestoodle/classes/gabarit/view_export.php: call to tool_attestoodle\gabarit\attestation_pdf->set_categoryid()
> 
> Output buffer: <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/html/moodle/admin/tool/attestoodle/classes/gabarit/attestation_pdf.php</b> on line <b>97</b><br /> 

Je suis allé voir en base et j'ai : 
```
MariaDB [moodle]> select * from mdl_tool_attestoodle_tpl_detail;
+----+------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id | templateid | type         | data                                                                                                                                                                |
+----+------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  1 |          1 | background   | { "filename": "attest_background.png" }                                                                                                                             |
|  2 |          1 | learnername  | { "font": {"family":"helvetica","emphasis":"","size":"14"}, "location": {"x":"66","y":"33"}, "align":"L"}                                                           |
|  3 |          1 | trainingname | { "font": {"family":"helvetica","emphasis":"","size":"14"}, "location": {"x":"66","y":"39"}, "align":"L"}                                                           |
|  4 |          1 | period       | { "font": {"family":"helvetica","emphasis":"B","size":"14"}, "location": {"x":"110","y":"18"}, "align":"L"}                                                         |
|  5 |          1 | totalminutes | { "font": {"family":"helvetica","emphasis":"B","size":"14"}, "location": {"x":"86","y":"45"}, "align":"L"}                                                          |
|  6 |          1 | activities   | { "font": {"family":"helvetica","emphasis":"","size":"10"}, "location": {"x":"50","y":"60"}, "align":"C"}                                                           |
| 17 |          2 | background   | {"filename":"fond_iae_2.png"}                                                                                                                                       |
| 18 |          2 | learnername  | {"font":{"family":"helvetica","emphasis":"","size":"12"},"location":{"x":16,"y":122},"align":"L","lib":"Nom du stagiaire : "}                                       |
| 19 |          2 | trainingname | {"font":{"family":"helvetica","emphasis":"","size":"12"},"location":{"x":16,"y":130},"align":"L","lib":"Intitul\u00e9 de la formation : "}                          |
| 20 |          2 | period       | {"font":{"family":"helvetica","emphasis":"B","size":"12"},"location":{"x":16,"y":138},"align":"L","lib":"Pour la p\u00e9riode "}                                    |
| 21 |          2 | totalminutes | {"font":{"family":"helvetica","emphasis":"B","size":"14"},"location":{"x":16,"y":159},"align":"L","lib":"Temps d'apprenstissage valid\u00e9 sur le mois : "}        |
| 22 |          2 | activities   | {"font":{"family":"helvetica","emphasis":"","size":"10"},"location":{"x":0,"y":168},"align":"C","size":170}                                                         |
| 23 |          2 | text         | {"font":{"family":"helvetica","emphasis":"","size":"10"},"location":{"x":16,"y":229},"align":"L","lib":"Cette attestation est faite pour valider ce que de droit."} |
| 24 |          2 | text         | {"font":{"family":"helvetica","emphasis":"","size":"10"},"location":{"x":16,"y":238},"align":"L","lib":"A Caen, le "}                                               |
| 25 |          2 | pagebreak    | {"numpage":"any","repeatbackground":true,"repeatstart":false,"repeatend":false}                                                                                     |
| 26 |          2 | pagenumber   | {"font":{"family":"courier","emphasis":"","size":"6"},"location":{"x":0,"y":285},"align":"C","ontotal":true}                                                        |
+----+------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
16 rows in set (0.00 sec)

MariaDB [moodle]> select * from mdl_tool_attestoodle_template;
+----+---------+-------------+--------+--------------+
| id | name    | timecreated | userid | timemodified |
+----+---------+-------------+--------+--------------+
|  1 | Site    |  1541673548 |      2 |         NULL |
|  2 | IAE-CGE |  1540924867 |  34436 |         NULL |
+----+---------+-------------+--------+--------------+
2 rows in set (0.00 sec)
```
**Je n'ai pas eu ce bug sur notre plateforme de préprod.**

**Comment by cemu-guillaumegirard** [comment]
@dcadiou Comment as-tu installé le plug-in sur ton docker ?

**Comment by cemu-guillaumegirard** [comment]
Commentaire par mail :

> Erreur à la génération d'attestations : c'est un problème de cohérence des données, la formation n'est pas reliée à un modèle, la table en erreur est 'tool_attestoodle_train_style'

**Comment by dcadiou** [comment]
C'est tout à fait juste.
J'ai un enregistrement dans  'tool_attestoodle_train_style' qui mentionne une formation d'id 2, alors que la seule existante a, en réalité, l'id 1.

Il ne s'agit donc pas d'un bug, mais d'un soucis introduit par mes soins quand j'ai intégré les données de modèle directement en base (sans passé par l'interface graphique d'attestoodle). Quand j'ai mis en place l'infra docker, je voulais aller vite et ne pas perdre de temps à renseigner toutes les données d'une formation suivi par attestoodle, comme celle que nous utilisons en prod actuellement. J'ai donc opté pour des copier coller des données Attestoodle de prod vers l'infra docker. Mais je ne suis pas allé assez loin et j'ai introduit des incohérences. C'est donc ma faute.
