### ISSUE TITLE
Modèle : positionnement inattendu des éléments centrés

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#8]
J'ai voulu créé un modèle avec des éléments centrés (par exemple le litteral 3).

Au format A4, j'ai considéré que le milieu était 105 (mm). J'ai réglé l'alignement sur centré.

J'obtiens l'aperçu ci-cjoint
[attestoodle_modele_iae-2.pdf](https://github.com/grp-attestoodle/attestoodle/files/2496659/attestoodle_modele_iae-2.pdf)

avec les réglages également joint (extraits de la table mdl_attestoodle_template_detail)
[attestoodle-modele-iae-2.csv.txt](https://github.com/grp-attestoodle/attestoodle/files/2496662/attestoodle-modele-iae-2.csv.txt)

**Comment by dcadiou** [comment]
J'ai oublié de préciser la version utilisée : 077bc94

**Comment by mleconte** [comment]
Pour centrer il suffit de mettre x=0 et align=C si x = 105 le centrage est réalisé sur la partie droit de la page avec une taille de tableau au minimum de 80mm.

**Comment by dcadiou** [comment]
J'ai testé : effectivement ça règle le problème. Il ne s'agissait donc pas d'un bug, mais d'un mauvais usage de ma part.
On peut clore.
