### ISSUE TITLE
Rapport global formation : Erreur si aucun apprenant

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/attestoodle#9]
Cette formation n'a pour l'instant qu'un seul jalon et aucun étudiant avec une activité achevée et très probablement pas d'étudiants inscrits dans les cours.

On a bien un message indiquant qu'il n'y a pas d'aprenant, mais il y a aussi une ou des erreurs.
Par ailleurs le message n'est pas affiché très longtemps, la page de gestion de la formation est réaffichée après quelques secondes seulement. Il est donc très (trop) facile de ne pas voir le message et de ne pas comprendre pourquoi le rapport ne s'est pas ouvert.

**Comment by dcadiou** [comment]
Copie d'écran :
![attestoodle-issue9-1](https://user-images.githubusercontent.com/25685520/47232904-5a374f80-d3d1-11e8-9103-ec01deeefaea.png)

**Comment by mleconte** [comment]
correction réalisée avec le commit 36bd4f6.
La redirection est effectuée plus tôt

**Comment by mleconte** [comment]
Correction effectuée avec le commit 36bd4f6
